### ISSUE TITLE
Having hard times with config 16 days per month <-> 28 days worked well

### ISSUE THREAD

**Issue by drkoaeg** [CallMeFoxie/Calendar#12]
---- Minecraft Crash Report ----
 // Sorry :(

Time: 22.09.17 10:05
 Description: Initializing game

java.lang.IllegalArgumentException: There is no such day in this month!
 at foxie.calendar.implementation.CalendarImpl.setDay(CalendarImpl.java:99)
 at foxie.calendar.implementation.SeasonProvider.(SeasonProvider.java:26)
 at foxie.calendar.Calendar.preinit(Calendar.java:38)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
 at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
 at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
 at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
 at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
 Stacktrace:
 at foxie.calendar.implementation.CalendarImpl.setDay(CalendarImpl.java:99)
 at foxie.calendar.implementation.SeasonProvider.(SeasonProvider.java:26)
 at foxie.calendar.Calendar.preinit(Calendar.java:38)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
 at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
 at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
 at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
 at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
 Details:
 Stacktrace:
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:483)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
 Details:
 Minecraft Version: 1.7.10
 Operating System: Windows 8.1 (amd64) version 6.3
 Java Version: 1.8.0_25, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 509734384 bytes (486 MB) / 898879488 bytes (857 MB) up to 4697620480 bytes (4480 MB)
 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1G -Xmx5G -XX:NewSize=1280M -XX:MaxNewSize=2560M -XX:SurvivorRatio=2 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts
 AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D7S_pre 110 mods loaded, 110 mods active
 States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 UCH mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
 UCH FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar)
 UCH Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar)
 UCH tfc_coremod{0.79.29} [TFC[coremod]] (minecraft.jar)
 UCH CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar)
 UCH NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar)
 UCH terrafirmacraft{0.79.29} [TerraFirmaCraft_TNFC] ([1.7.10]TerraFirmaCraft-0.79.29.tnfc.6644d46.jar)
 UCE CalendarAPI{@Version@} [CalendarAPI] (Calendar-1.7.10-1.0-4.jar)
 UCH McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
 UCH TerraFirmaCraftNEIplugin{1.5.3.24} [TerraFirmaCraftNEIplugin] (TerraFirmaCraftNEIplugin-1.7.10-1.5.3.24.jar)
 UCH FMPIntegration{1.0} [FMPIntegration] ([1.7.10]FMPIntegration-1.2.2.jar)
 UCH ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
 GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.65' Renderer: 'GeForce GT 520M/PCIe/SSE2'
 Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
 LWJGL: 2.9.1
 OpenGL: GeForce GT 520M/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.65, NVIDIA Corporation
 GL Caps: Using GL 1.3 multitexturing.
 Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
 Anisotropic filtering is supported and maximum anisotropy is 16.
 Shaders are available because OpenGL 2.1 is supported.
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Conquest_.zip]
Current Language: Deutsch (Deutschland)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
OptiFine Version: OptiFine_1.7.10_HD_U_D7S_pre
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 381.65
OpenGlRenderer: GeForce GT 520M/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4

**Comment by CallMeFoxie** [comment]
and config?

**Comment by drkoaeg** [comment]
# Configuration file

calendar {
    # Days in months
    # Changing for existing worlds will recalculate it
    I:days <
        14
        14
        14
        14
        14
        14
        14
        14
        14
        14
        14
        14
        14
     >

    # Named months [default: [January], [February], [March], [April], [May], [June], [July], [August], [September], [October], [November], [December]]
    S:monthNames <
        January
        February
        March
        April
        May
        June
        July
        August
        September
        October
        November
        December
     >
}


config {
    # Enable date command [default: true]
    B:enableDateCommand=true

    # Enable fixed time command [default: true]
    B:enableFixedTimeCommand=true

    # Enable season command [default: true]
    B:enableSeasonCommand=true
}


seasons {
    # Starting temperature of the season (K) [range: 0 ~ 1000, default: 295]
    I:autumn_begin_temp=295

    # Beginning day for autumn [range: 0 ~ 30, default: 21]
    I:autumn_day_begin=12

    # Temperature at the end of the season (K) [range: 0 ~ 1000, default: 270]
    I:autumn_end_temp=270

    # Temperature in the middle of the season (K) [range: 0 ~ 1000, default: 280]
    I:autumn_mid_temp=280

    # Beginning month for autumn [range: 0 ~ 12, default: 8]
    I:autumn_month_begin=8

    # Names of the seasons [default: [winter], [summer], [spring], [autumn]]
    S:seasons <
        winter
        summer
        spring
        autumn
     >

    # Starting temperature of the season (K) [range: 0 ~ 1000, default: 260]
    I:spring_begin_temp=260

    # Beginning day for spring [range: 0 ~ 31, default: 21]
    I:spring_day_begin=12

    # Temperature at the end of the season (K) [range: 0 ~ 1000, default: 285]
    I:spring_end_temp=285

    # Temperature in the middle of the season (K) [range: 0 ~ 1000, default: 280]
    I:spring_mid_temp=280

    # Beginning month for spring [range: 0 ~ 12, default: 2]
    I:spring_month_begin=2

    # Starting temperature of the season (K) [range: 0 ~ 1000, default: 285]
    I:summer_begin_temp=285

    # Beginning day for summer [range: 0 ~ 30, default: 21]
    I:summer_day_begin=12

    # Temperature at the end of the season (K) [range: 0 ~ 1000, default: 295]
    I:summer_end_temp=295

    # Temperature in the middle of the season (K) [range: 0 ~ 1000, default: 303]
    I:summer_mid_temp=303

    # Beginning month for summer [range: 0 ~ 12, default: 5]
    I:summer_month_begin=5

    # Starting temperature of the season (K) [range: 0 ~ 1000, default: 270]
    I:winter_begin_temp=270

    # Beginning day for winter [range: 0 ~ 31, default: 21]
    I:winter_day_begin=12

    # Temperature at the end of the season (K) [range: 0 ~ 1000, default: 260]
    I:winter_end_temp=260

    # Temperature in the middle of the season (K) [range: 0 ~ 1000, default: 240]
    I:winter_mid_temp=240

    # Beginning month for winter [range: 0 ~ 12, default: 11]
    I:winter_month_begin=11
}

**Comment by drkoaeg** [comment]
Sorry for the mess I can also upload the file...

**Comment by drkoaeg** [comment]
In this config I tried 14 days instead of 16 because at first I thought it might must be divisible by 7.

**Comment by CallMeFoxie** [comment]
In 
I:days
I see 13 items
whereas in
S:monthNames 
I see only 12 items?

Also when does the stacktrace happen?

**Comment by CallMeFoxie** [comment]
oh I think I know why, it's in SeasonProvider.java the default values before config is properly loaded. I will fix it.

**Comment by drkoaeg** [comment]
Thank you so much. Yes, ..ehrm.. in the last try I must have copied the numbers one time more...my bad

**Comment by CallMeFoxie** [comment]
Try this
https://jenkins.foxiehost.eu/job/Calendar%20-%20master/lastSuccessfulBuild/artifact/build/libs/Calendar-1.11.2-1.5-12.jar

for MC 1.11.2

**Comment by drkoaeg** [comment]
would you please also fix it in the 1.7.10 version, I use? I know it has been some time since, but please

**Comment by CallMeFoxie** [comment]
https://jenkins.foxiehost.eu/job/Calendar%20-%201.7.10/lastSuccessfulBuild/artifact/build/libs/Calendar-1.7.10-1.0-10.jar

Here :)

**Comment by drkoaeg** [comment]
Thank you so much, I have tested, everything is fine! :)

**Comment by CallMeFoxie** [comment]
Glad it works! Will throw it on curseforge later.
